namespace Yunu.Commerce.Catalog.Application.CategoryResolution;

/// <summary>
/// Thrown when the embedding actually generated by the resolved <see
/// cref="Yunu.Commerce.AI.Application.Embeddings.IEmbeddingProvider"/> does
/// not match the deployment registered for the "CategoryEmbedding" logical
/// model (docs task: "Google Category Resolution"). This guards against
/// silently comparing vectors produced by two different embedding models,
/// mirroring <see
/// cref="Yunu.Commerce.Catalog.Application.AttributeResolution.AttributeResolutionEmbeddingModelMismatchException"/>.
/// </summary>
public sealed class CategoryResolutionEmbeddingModelMismatchException : Exception
{
    public CategoryResolutionEmbeddingModelMismatchException(string expectedDeploymentName, string actualModel)
        : base($"Expected embeddings generated with deployment '{expectedDeploymentName}' but received '{actualModel}'. " +
               "Category resolution must use the same embedding model that generated the stored Google Taxonomy category embeddings.")
    {
    }
}
