<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- shared compilation settings inherited from Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Yunu.Commerce.Contracts/Yunu.Commerce.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>

  </ItemGroup>

</Project>
