using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Options;
using Testcontainers.MsSql;
using Xunit;
using Yunu.Commerce.Catalog.Domain.Segments;
using Yunu.Commerce.Catalog.Infrastructure.GoogleTaxonomy.Persistence.SqlServer;
using Yunu.Commerce.Catalog.Infrastructure.SegmentCatalog.SqlServer;

namespace Yunu.Commerce.Catalog.IntegrationTests;

/// <summary>
/// Integration tests for the write-side SqlSegmentDefinitionRepository
/// against a real SQL Server instance via Testcontainers (docs task:
/// "Canonical Taxonomy + Segments Domain"). The schema is created the same
/// way as SqlSegmentCatalogRepositoryTests, by executing
/// deploy/databases/sqlserver/006-create-canonical-taxonomy-segmentation.sql
/// and deploy/databases/sqlserver/008-add-segment-assignment-scope.sql
/// directly against the container. Assertions never depend on the specific
/// numeric IDs generated by the seed data or by other tests.
/// </summary>
public sealed class SqlSegmentDefinitionRepositoryTests : IAsyncLifetime
{
    private readonly MsSqlContainer _sqlContainer = new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();
    private SqlSegmentDefinitionRepository _repository = null!;
    private string _connectionString = null!;

    public async Task InitializeAsync()
    {
        await _sqlContainer.StartAsync();

        _connectionString = _sqlContainer.GetConnectionString();

        await RunScriptAsync(_connectionString, "006-create-canonical-taxonomy-segmentation.sql");
        await RunScriptAsync(_connectionString, "008-add-segment-assignment-scope.sql");

        var options = Options.Create(new GoogleTaxonomySqlOptions
        {
            ConnectionString = _connectionString
        });

        _repository = new SqlSegmentDefinitionRepository(options);
    }

    public async Task DisposeAsync()
    {
        await _sqlContainer.DisposeAsync();
    }

    private static async Task RunScriptAsync(string connectionString, string fileName)
    {
        var scriptPath = Path.Combine(
            AppContext.BaseDirectory,
            "..", "..", "..", "..", "..", "..",
            "deploy", "databases", "sqlserver", fileName);

        var script = await File.ReadAllTextAsync(Path.GetFullPath(scriptPath));

        await using var connection = new SqlConnection(connectionString);
        await connection.OpenAsync();

        foreach (var batch in script.Split("GO", StringSplitOptions.RemoveEmptyEntries))
        {
            if (string.IsNullOrWhiteSpace(batch))
            {
                continue;
            }

            await using var command = new SqlCommand(batch, connection);
            await command.ExecuteNonQueryAsync();
        }
    }

    private static SegmentDefinition NewDraftDefinition(string code, string name)
    {
        return SegmentDefinition.Create(
            new SegmentDefinitionCode(code),
            new SegmentDefinitionName(name),
            "Some description",
            "Some semantic text",
            SegmentSelectionMode.Single,
            SegmentAssignmentScope.Product,
            isRequired: true);
    }

    [Fact]
    public async Task AddAsync_generates_id_greater_than_zero()
    {
        var definition = NewDraftDefinition("integration_add_id", "Integration Add Id");

        var id = await _repository.AddAsync(definition, CancellationToken.None);

        Assert.True(id.Value > 0);
    }

    [Fact]
    public async Task AddAsync_persists_all_fields()
    {
        var definition = NewDraftDefinition("integration_add_fields", "Integration Add Fields");

        var id = await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal("integration_add_fields", persisted!.Code.Value);
        Assert.Equal("Integration Add Fields", persisted.Name.Value);
        Assert.Equal("INTEGRATION ADD FIELDS", persisted.NormalizedName);
        Assert.Equal("Some description", persisted.Description);
        Assert.Equal("Some semantic text", persisted.SemanticText);
        Assert.Equal(SegmentSelectionMode.Single, persisted.SelectionMode);
        Assert.Equal(SegmentAssignmentScope.Product, persisted.AssignmentScope);
        Assert.True(persisted.IsRequired);
        Assert.Equal(SegmentDefinitionStatus.Draft, persisted.Status);
    }

    [Fact]
    public async Task GetByIdAsync_hydrates_correctly()
    {
        var definition = NewDraftDefinition("integration_get_by_id", "Integration Get By Id");
        var id = await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal(id, persisted!.Id);
    }

    [Fact]
    public async Task GetByCodeAsync_finds_record()
    {
        var definition = NewDraftDefinition("integration_get_by_code", "Integration Get By Code");
        await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByCodeAsync(new SegmentDefinitionCode("integration_get_by_code"), CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal("integration_get_by_code", persisted!.Code.Value);
    }

    [Fact]
    public async Task FindByNormalizedNameAsync_finds_record()
    {
        var definition = NewDraftDefinition("integration_find_by_norm", "Integration Find By Norm");
        await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.FindByNormalizedNameAsync("INTEGRATION FIND BY NORM", CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal("integration_find_by_norm", persisted!.Code.Value);
    }

    [Fact]
    public async Task UpdateAsync_persists_mutable_fields()
    {
        var definition = NewDraftDefinition("integration_update", "Integration Update");
        var id = await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);
        persisted!.Update(
            new SegmentDefinitionName("Integration Update Renamed"),
            "Updated description",
            "Updated semantic text",
            persisted.SelectionMode,
            persisted.AssignmentScope,
            persisted.IsRequired,
            SegmentDefinitionStatus.Active);

        await _repository.UpdateAsync(persisted, CancellationToken.None);

        var reloaded = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(reloaded);
        Assert.Equal("Integration Update Renamed", reloaded!.Name.Value);
        Assert.Equal("INTEGRATION UPDATE RENAMED", reloaded.NormalizedName);
        Assert.Equal("Updated description", reloaded.Description);
        Assert.Equal("Updated semantic text", reloaded.SemanticText);
        Assert.Equal(SegmentDefinitionStatus.Active, reloaded.Status);
    }

    [Fact]
    public async Task UpdateAsync_does_not_change_code()
    {
        var definition = NewDraftDefinition("integration_update_code", "Integration Update Code");
        var id = await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);
        persisted!.Update(
            new SegmentDefinitionName("Renamed"),
            persisted.Description,
            persisted.SemanticText,
            persisted.SelectionMode,
            persisted.AssignmentScope,
            persisted.IsRequired,
            persisted.Status);

        await _repository.UpdateAsync(persisted, CancellationToken.None);

        var reloaded = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.Equal("integration_update_code", reloaded!.Code.Value);
    }

    [Fact]
    public async Task UpdateAsync_updates_updatedat()
    {
        const string connectionQuery = "SELECT UpdatedAt FROM Catalog.SegmentDefinitions WHERE SegmentDefinitionId = @Id";

        var definition = NewDraftDefinition("integration_update_updatedat", "Integration Update UpdatedAt");
        var id = await _repository.AddAsync(definition, CancellationToken.None);

        DateTime beforeUpdatedAt;
        await using (var connection = new SqlConnection(_connectionString))
        {
            await connection.OpenAsync();
            await using var command = new SqlCommand(connectionQuery, connection);
            command.Parameters.AddWithValue("@Id", id.Value);
            beforeUpdatedAt = (DateTime)(await command.ExecuteScalarAsync())!;
        }

        await Task.Delay(50);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);
        persisted!.Update(
            persisted.Name,
            persisted.Description,
            persisted.SemanticText,
            persisted.SelectionMode,
            persisted.AssignmentScope,
            persisted.IsRequired,
            persisted.Status);
        await _repository.UpdateAsync(persisted, CancellationToken.None);

        DateTime afterUpdatedAt;
        await using (var connection = new SqlConnection(_connectionString))
        {
            await connection.OpenAsync();
            await using var command = new SqlCommand(connectionQuery, connection);
            command.Parameters.AddWithValue("@Id", id.Value);
            afterUpdatedAt = (DateTime)(await command.ExecuteScalarAsync())!;
        }

        Assert.True(afterUpdatedAt > beforeUpdatedAt);
    }

    [Fact]
    public async Task AddAsync_rejects_definition_with_existing_id()
    {
        var definition = NewDraftDefinition("integration_add_with_id", "Integration Add With Id");
        var id = await _repository.AddAsync(definition, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        await Assert.ThrowsAsync<InvalidOperationException>(() => _repository.AddAsync(persisted!, CancellationToken.None));
    }

    [Fact]
    public async Task UpdateAsync_rejects_definition_without_id()
    {
        var definition = NewDraftDefinition("integration_update_no_id", "Integration Update No Id");

        await Assert.ThrowsAsync<InvalidOperationException>(() => _repository.UpdateAsync(definition, CancellationToken.None));
    }
}
