using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Options;
using Testcontainers.MsSql;
using Xunit;
using Yunu.Commerce.Catalog.Domain.Segments;
using Yunu.Commerce.Catalog.Infrastructure.GoogleTaxonomy.Persistence.SqlServer;
using Yunu.Commerce.Catalog.Infrastructure.SegmentCatalog.SqlServer;

namespace Yunu.Commerce.Catalog.IntegrationTests;

/// <summary>
/// Integration tests for the write-side SqlSegmentOptionRepository against a
/// real SQL Server instance via Testcontainers (docs task: "Implementar
/// Domain + Write-Side de SegmentOption"), mirroring
/// SqlSegmentDefinitionRepositoryTests. The schema is created the same way,
/// by executing
/// deploy/databases/sqlserver/006-create-canonical-taxonomy-segmentation.sql
/// and deploy/databases/sqlserver/008-add-segment-assignment-scope.sql
/// directly against the container. Assertions never depend on the specific
/// numeric IDs generated by the seed data or by other tests.
/// </summary>
public sealed class SqlSegmentOptionRepositoryTests : IAsyncLifetime
{
    private readonly MsSqlContainer _sqlContainer = new MsSqlBuilder("mcr.microsoft.com/mssql/server:2022-latest").Build();
    private SqlSegmentOptionRepository _repository = null!;
    private SqlSegmentDefinitionRepository _definitionRepository = null!;
    private string _connectionString = null!;

    public async Task InitializeAsync()
    {
        await _sqlContainer.StartAsync();

        _connectionString = _sqlContainer.GetConnectionString();

        await RunScriptAsync(_connectionString, "006-create-canonical-taxonomy-segmentation.sql");
        await RunScriptAsync(_connectionString, "008-add-segment-assignment-scope.sql");

        var options = Options.Create(new GoogleTaxonomySqlOptions
        {
            ConnectionString = _connectionString
        });

        _repository = new SqlSegmentOptionRepository(options);
        _definitionRepository = new SqlSegmentDefinitionRepository(options);
    }

    public async Task DisposeAsync()
    {
        await _sqlContainer.DisposeAsync();
    }

    private static async Task RunScriptAsync(string connectionString, string fileName)
    {
        var scriptPath = Path.Combine(
            AppContext.BaseDirectory,
            "..", "..", "..", "..", "..", "..",
            "deploy", "databases", "sqlserver", fileName);

        var script = await File.ReadAllTextAsync(Path.GetFullPath(scriptPath));

        await using var connection = new SqlConnection(connectionString);
        await connection.OpenAsync();

        foreach (var batch in script.Split("GO", StringSplitOptions.RemoveEmptyEntries))
        {
            if (string.IsNullOrWhiteSpace(batch))
            {
                continue;
            }

            await using var command = new SqlCommand(batch, connection);
            await command.ExecuteNonQueryAsync();
        }
    }

    private async Task<SegmentDefinitionId> CreateDefinitionAsync(string code, string name)
    {
        var definition = SegmentDefinition.Create(
            new SegmentDefinitionCode(code),
            new SegmentDefinitionName(name),
            "Some description",
            "Some semantic text",
            SegmentSelectionMode.Single,
            SegmentAssignmentScope.Product);

        return await _definitionRepository.AddAsync(definition, CancellationToken.None);
    }

    private static SegmentOption NewDraftOption(SegmentDefinitionId segmentDefinitionId, string code, string name)
    {
        return SegmentOption.Create(
            segmentDefinitionId,
            new SegmentOptionCode(code),
            new SegmentOptionName(name),
            "Some option description",
            "Some option semantic text",
            10);
    }

    [Fact]
    public async Task AddAsync_generates_id_greater_than_zero()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_add_id", "Integration Option Add Id");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_A", "Option A");

        var id = await _repository.AddAsync(option, CancellationToken.None);

        Assert.True(id.Value > 0);
    }

    [Fact]
    public async Task AddAsync_persists_all_fields()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_add_fields", "Integration Option Add Fields");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_B", "Option B");

        var id = await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal(segmentDefinitionId, persisted!.SegmentDefinitionId);
        Assert.Equal("OPTION_B", persisted.Code.Value);
        Assert.Equal("Option B", persisted.Name.Value);
        Assert.Equal("OPTION B", persisted.NormalizedName);
        Assert.Equal("Some option description", persisted.Description);
        Assert.Equal("Some option semantic text", persisted.SemanticText);
        Assert.Equal(10, persisted.DisplayOrder);
        Assert.Equal(SegmentOptionStatus.Draft, persisted.Status);
    }

    [Fact]
    public async Task GetByIdAsync_hydrates_correctly()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_get_by_id", "Integration Option Get By Id");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_C", "Option C");
        var id = await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal(id, persisted!.Id);
    }

    [Fact]
    public async Task GetByCodeAsync_finds_record()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_get_by_code", "Integration Option Get By Code");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_D", "Option D");
        await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByCodeAsync(segmentDefinitionId, new SegmentOptionCode("OPTION_D"), CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal("OPTION_D", persisted!.Code.Value);
    }

    [Fact]
    public async Task FindByNormalizedNameAsync_finds_record()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_find_by_norm", "Integration Option Find By Norm");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_E", "Option E Name");
        await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.FindByNormalizedNameAsync(segmentDefinitionId, "OPTION E NAME", CancellationToken.None);

        Assert.NotNull(persisted);
        Assert.Equal("OPTION_E", persisted!.Code.Value);
    }

    [Fact]
    public async Task ExistsCodeAsync_is_scoped_to_segment_definition()
    {
        var firstDefinitionId = await CreateDefinitionAsync("integration_option_scope_a", "Integration Option Scope A");
        var secondDefinitionId = await CreateDefinitionAsync("integration_option_scope_b", "Integration Option Scope B");

        var option = NewDraftOption(firstDefinitionId, "SHARED_CODE", "Shared Code Option");
        await _repository.AddAsync(option, CancellationToken.None);

        var existsInOwner = await _repository.ExistsCodeAsync(firstDefinitionId, new SegmentOptionCode("SHARED_CODE"), CancellationToken.None);
        var existsInOther = await _repository.ExistsCodeAsync(secondDefinitionId, new SegmentOptionCode("SHARED_CODE"), CancellationToken.None);

        Assert.True(existsInOwner);
        Assert.False(existsInOther);
    }

    [Fact]
    public async Task UpdateAsync_persists_mutable_fields()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_update", "Integration Option Update");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_F", "Option F");
        var id = await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);
        persisted!.Update(
            new SegmentOptionName("Option F Renamed"),
            "Updated description",
            "Updated semantic text",
            20,
            SegmentOptionStatus.Active);

        await _repository.UpdateAsync(persisted, CancellationToken.None);

        var reloaded = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.NotNull(reloaded);
        Assert.Equal("Option F Renamed", reloaded!.Name.Value);
        Assert.Equal("OPTION F RENAMED", reloaded.NormalizedName);
        Assert.Equal("Updated description", reloaded.Description);
        Assert.Equal("Updated semantic text", reloaded.SemanticText);
        Assert.Equal(20, reloaded.DisplayOrder);
        Assert.Equal(SegmentOptionStatus.Active, reloaded.Status);
    }

    [Fact]
    public async Task UpdateAsync_does_not_change_code_or_segment_definition_id()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_update_code", "Integration Option Update Code");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_G", "Option G");
        var id = await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);
        persisted!.Update(
            new SegmentOptionName("Renamed"),
            persisted.Description,
            persisted.SemanticText,
            persisted.DisplayOrder,
            persisted.Status);

        await _repository.UpdateAsync(persisted, CancellationToken.None);

        var reloaded = await _repository.GetByIdAsync(id, CancellationToken.None);

        Assert.Equal("OPTION_G", reloaded!.Code.Value);
        Assert.Equal(segmentDefinitionId, reloaded.SegmentDefinitionId);
    }

    [Fact]
    public async Task AddAsync_rejects_option_with_existing_id()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_add_with_id", "Integration Option Add With Id");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_H", "Option H");
        var id = await _repository.AddAsync(option, CancellationToken.None);

        var persisted = await _repository.GetByIdAsync(id, CancellationToken.None);

        await Assert.ThrowsAsync<InvalidOperationException>(() => _repository.AddAsync(persisted!, CancellationToken.None));
    }

    [Fact]
    public async Task UpdateAsync_rejects_option_without_id()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_update_no_id", "Integration Option Update No Id");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_I", "Option I");

        await Assert.ThrowsAsync<InvalidOperationException>(() => _repository.UpdateAsync(option, CancellationToken.None));
    }

    [Fact]
    public async Task AddAsync_rejects_duplicate_code_within_same_definition()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_dup_code", "Integration Option Dup Code");
        var first = NewDraftOption(segmentDefinitionId, "DUP_CODE", "First");
        await _repository.AddAsync(first, CancellationToken.None);

        var second = NewDraftOption(segmentDefinitionId, "DUP_CODE", "Second");

        await Assert.ThrowsAsync<SqlException>(() => _repository.AddAsync(second, CancellationToken.None));
    }

    [Fact]
    public async Task GetOptionsByDefinitionAsync_read_side_sees_persisted_option()
    {
        var segmentDefinitionId = await CreateDefinitionAsync("integration_option_read_side", "Integration Option Read Side");
        var option = NewDraftOption(segmentDefinitionId, "OPTION_J", "Option J");
        await _repository.AddAsync(option, CancellationToken.None);

        var readRepository = new SqlSegmentCatalogRepository(Options.Create(new GoogleTaxonomySqlOptions
        {
            ConnectionString = _connectionString
        }));

        var options = await readRepository.GetOptionsByDefinitionAsync(segmentDefinitionId.Value, CancellationToken.None);

        Assert.Contains(options, o => o.Code == "OPTION_J");
    }
}
