<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Modules/Catalog/Yunu.Commerce.Catalog.Domain/Yunu.Commerce.Catalog.Domain.csproj" />
    <ProjectReference Include="../../../src/Modules/Catalog/Yunu.Commerce.Catalog.Application/Yunu.Commerce.Catalog.Application.csproj" />
    <ProjectReference Include="../../../src/Modules/Catalog/Yunu.Commerce.Catalog.Infrastructure/Yunu.Commerce.Catalog.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.MongoDb" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
