<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- shared compilation settings inherited from Directory.Build.props -->
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Yunu.Commerce.Offers.Domain/Yunu.Commerce.Offers.Domain.csproj" />
    <ProjectReference Include="../Yunu.Commerce.Offers.Application/Yunu.Commerce.Offers.Application.csproj" />
    <ProjectReference Include="../Yunu.Commerce.Offers.Contracts/Yunu.Commerce.Offers.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Yunu.Commerce.EventBus/Yunu.Commerce.EventBus.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Yunu.Commerce.Observability/Yunu.Commerce.Observability.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

</Project>
