namespace Yunu.Commerce.Catalog.Application.AttributeResolution;

/// <summary>
/// Thrown when the embedding actually generated by the resolved
/// <see cref="Yunu.Commerce.AI.Application.Embeddings.IEmbeddingProvider"/>
/// does not match the deployment registered for the "CategoryEmbedding"
/// logical model (docs task: "Semantic attribute hint resolution",
/// authorization item 3). This guards against silently comparing vectors
/// produced by two different embedding models once more providers/models are
/// registered.
/// </summary>
public sealed class AttributeResolutionEmbeddingModelMismatchException : Exception
{
    public AttributeResolutionEmbeddingModelMismatchException(string expectedDeploymentName, string actualModel)
        : base($"Expected embeddings generated with deployment '{expectedDeploymentName}' but received '{actualModel}'. " +
               "Attribute resolution must use the same embedding model that generated the stored attribute embeddings.")
    {
    }
}
