#requires -Version 7.0
<#
.SYNOPSIS
    Idempotent bootstrap script for the Yunu.Commerce solution skeleton.

.DESCRIPTION
    Creates the .NET solution structure defined in docs/architecture/06-solution-structure.md:
    - Yunu.Commerce.sln with Visual Studio Solution Folders
    - src/BuildingBlocks, src/Modules/*, src/Hosts
    - tests/Architecture, tests/Unit, tests/Integration
    - Directory.Build.props, Directory.Packages.props, global.json, .editorconfig
    - Minimal API Host, Worker Host, Architecture Tests, DI extension points,
      health-check foundation and OpenTelemetry bootstrap.

    Re-running this script overwrites generated files with deterministic content
    and re-registers projects/references, which are no-ops if already present.

.NOTES
    Generated by GitHub Copilot from the Yunu.Commerce architecture documentation,
    `.github/copilot-instructions.md`, `docs/architecture/06-solution-structure.md`,
    and the accepted ADRs.

    Does NOT create business Aggregates, Entities, Value Objects or Domain rules.
    Does NOT reference MongoDB, Kafka, Redis, Elasticsearch, Azure AI or Google AI SDKs.
#>

[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [switch]$SkipTest
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Invoke-Checked {
    param(
        [Parameter(Mandatory)][string]$Exe,
        [Parameter(Mandatory)][string[]]$Arguments
    )
    Write-Host ">> $Exe $($Arguments -join ' ')" -ForegroundColor Cyan
    & $Exe @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed with exit code $LASTEXITCODE : $Exe $($Arguments -join ' ')"
    }
}

function Write-TextFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Content
    )
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Force -Path $dir | Out-Null
    }
    Set-Content -Path $Path -Value $Content -Encoding UTF8
    Write-Host "  wrote $($Path.Substring($root.Length + 1))"
}

# ---------------------------------------------------------------------------
# Project registry
# ---------------------------------------------------------------------------

$projects = [ordered]@{}

function Add-ProjectDef {
    param(
        [Parameter(Mandatory)][string]$Name,
        [Parameter(Mandatory)][string]$Dir,
        [string]$Sdk = 'Microsoft.NET.Sdk',
        [string[]]$ProjectRefs = @(),
        [string[]]$Packages = @(),
        [Parameter(Mandatory)][string]$SolutionFolder,
        [string]$Kind = 'lib'
    )
    $projects[$Name] = [ordered]@{
        Name           = $Name
        Dir            = $Dir
        Sdk            = $Sdk
        ProjectRefs    = $ProjectRefs
        Packages       = $Packages
        SolutionFolder = $SolutionFolder
        Kind           = $Kind
    }
}

# --- BuildingBlocks (docs/architecture/06-solution-structure.md §9-14) -----

Add-ProjectDef -Name 'Yunu.Commerce.SharedKernel' -Dir 'src/BuildingBlocks/Yunu.Commerce.SharedKernel' `
    -SolutionFolder 'BuildingBlocks'

Add-ProjectDef -Name 'Yunu.Commerce.Contracts' -Dir 'src/BuildingBlocks/Yunu.Commerce.Contracts' `
    -SolutionFolder 'BuildingBlocks'

Add-ProjectDef -Name 'Yunu.Commerce.EventBus' -Dir 'src/BuildingBlocks/Yunu.Commerce.EventBus' `
    -ProjectRefs @('Yunu.Commerce.Contracts') `
    -SolutionFolder 'BuildingBlocks'

Add-ProjectDef -Name 'Yunu.Commerce.Observability' -Dir 'src/BuildingBlocks/Yunu.Commerce.Observability' `
    -Packages @(
        'Microsoft.Extensions.Hosting.Abstractions',
        'Microsoft.Extensions.DependencyInjection.Abstractions',
        'OpenTelemetry',
        'OpenTelemetry.Extensions.Hosting',
        'OpenTelemetry.Exporter.Console'
    ) `
    -SolutionFolder 'BuildingBlocks'

Add-ProjectDef -Name 'Yunu.Commerce.Security' -Dir 'src/BuildingBlocks/Yunu.Commerce.Security' `
    -Packages @('Microsoft.Extensions.DependencyInjection.Abstractions') `
    -SolutionFolder 'BuildingBlocks'

# --- Business modules (Domain + Application + Infrastructure + Contracts) --

$businessModules = @('Catalog', 'Sellers', 'Offers', 'Pricing', 'Availability', 'Fulfillment', 'Freight')

# --- Supporting capabilities (no Domain project - §23/§24/§25) ------------

$supportModules = @('Search', 'AI', 'Integrations')

foreach ($m in $businessModules) {
    $base = "src/Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Domain" -Dir "$base/Yunu.Commerce.$m.Domain" `
        -ProjectRefs @('Yunu.Commerce.SharedKernel') `
        -SolutionFolder "Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Application" -Dir "$base/Yunu.Commerce.$m.Application" `
        -ProjectRefs @("Yunu.Commerce.$m.Domain", 'Yunu.Commerce.SharedKernel') `
        -Packages @('Microsoft.Extensions.DependencyInjection.Abstractions') `
        -SolutionFolder "Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Contracts" -Dir "$base/Yunu.Commerce.$m.Contracts" `
        -SolutionFolder "Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Infrastructure" -Dir "$base/Yunu.Commerce.$m.Infrastructure" `
        -ProjectRefs @(
            "Yunu.Commerce.$m.Domain",
            "Yunu.Commerce.$m.Application",
            "Yunu.Commerce.$m.Contracts",
            'Yunu.Commerce.EventBus',
            'Yunu.Commerce.Observability'
        ) `
        -Packages @(
            'Microsoft.Extensions.DependencyInjection.Abstractions',
            'Microsoft.Extensions.Configuration.Abstractions'
        ) `
        -SolutionFolder "Modules/$m"
}

foreach ($m in $supportModules) {
    $base = "src/Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Application" -Dir "$base/Yunu.Commerce.$m.Application" `
        -ProjectRefs @('Yunu.Commerce.SharedKernel') `
        -Packages @('Microsoft.Extensions.DependencyInjection.Abstractions') `
        -SolutionFolder "Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Contracts" -Dir "$base/Yunu.Commerce.$m.Contracts" `
        -SolutionFolder "Modules/$m"

    Add-ProjectDef -Name "Yunu.Commerce.$m.Infrastructure" -Dir "$base/Yunu.Commerce.$m.Infrastructure" `
        -ProjectRefs @(
            "Yunu.Commerce.$m.Application",
            "Yunu.Commerce.$m.Contracts",
            'Yunu.Commerce.EventBus',
            'Yunu.Commerce.Observability'
        ) `
        -Packages @(
            'Microsoft.Extensions.DependencyInjection.Abstractions',
            'Microsoft.Extensions.Configuration.Abstractions'
        ) `
        -SolutionFolder "Modules/$m"
}

$allModules = $businessModules + $supportModules

# --- Hosts (§6-8) -----------------------------------------------------------

$hostRefs = @()
foreach ($m in $allModules) {
    $hostRefs += "Yunu.Commerce.$m.Application"
    $hostRefs += "Yunu.Commerce.$m.Infrastructure"
}
$hostRefs += @(
    'Yunu.Commerce.SharedKernel',
    'Yunu.Commerce.Contracts',
    'Yunu.Commerce.EventBus',
    'Yunu.Commerce.Observability',
    'Yunu.Commerce.Security'
)

Add-ProjectDef -Name 'Yunu.Commerce.Api' -Dir 'src/Hosts/Yunu.Commerce.Api' `
    -Sdk 'Microsoft.NET.Sdk.Web' -ProjectRefs $hostRefs -SolutionFolder 'Hosts' -Kind 'api'

Add-ProjectDef -Name 'Yunu.Commerce.Worker' -Dir 'src/Hosts/Yunu.Commerce.Worker' `
    -Sdk 'Microsoft.NET.Sdk.Worker' -ProjectRefs $hostRefs `
    -Packages @('Microsoft.Extensions.Diagnostics.HealthChecks') `
    -SolutionFolder 'Hosts' -Kind 'worker'

# --- Tests (§40-42) ----------------------------------------------------------

$archRefs = @()
foreach ($m in $allModules) { $archRefs += "Yunu.Commerce.$m.Infrastructure" }

Add-ProjectDef -Name 'Yunu.Commerce.ArchitectureTests' -Dir 'tests/Architecture/Yunu.Commerce.ArchitectureTests' `
    -ProjectRefs $archRefs `
    -Packages @('Microsoft.NET.Test.Sdk', 'xunit', 'xunit.runner.visualstudio', 'NetArchTest.Rules') `
    -SolutionFolder 'Tests/Architecture' -Kind 'test'

foreach ($m in $businessModules) {
    Add-ProjectDef -Name "Yunu.Commerce.$m.Domain.Tests" -Dir "tests/Unit/Yunu.Commerce.$m.Domain.Tests" `
        -ProjectRefs @("Yunu.Commerce.$m.Domain") `
        -Packages @('Microsoft.NET.Test.Sdk', 'xunit', 'xunit.runner.visualstudio') `
        -SolutionFolder 'Tests/Unit' -Kind 'test'
}

Add-ProjectDef -Name 'Yunu.Commerce.Catalog.Application.Tests' -Dir 'tests/Unit/Yunu.Commerce.Catalog.Application.Tests' `
    -ProjectRefs @('Yunu.Commerce.Catalog.Application') `
    -Packages @('Microsoft.NET.Test.Sdk', 'xunit', 'xunit.runner.visualstudio') `
    -SolutionFolder 'Tests/Unit' -Kind 'test'

Add-ProjectDef -Name 'Yunu.Commerce.IntegrationTests' -Dir 'tests/Integration/Yunu.Commerce.IntegrationTests' `
    -ProjectRefs @('Yunu.Commerce.Api') `
    -Packages @('Microsoft.NET.Test.Sdk', 'xunit', 'xunit.runner.visualstudio') `
    -SolutionFolder 'Tests/Integration' -Kind 'test'

# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------

function New-CsprojContent {
    param([Parameter(Mandatory)]$Def)

    $refLines = @()
    foreach ($r in $Def.ProjectRefs) {
        $target = $projects[$r]
        $targetPath = Join-Path $root "$($target.Dir)/$($target.Name).csproj"
        $fromDir = Join-Path $root $Def.Dir
        $rel = [System.IO.Path]::GetRelativePath($fromDir, $targetPath) -replace '\\', '/'
        $refLines += "    <ProjectReference Include=""$rel"" />"
    }

    $pkgLines = @()
    foreach ($p in $Def.Packages) {
        $pkgLines += "    <PackageReference Include=""$p"" />"
    }

    $extraProps = ''
    if ($Def.Kind -eq 'test') {
        $extraProps = "    <IsPackable>false</IsPackable>`n    <IsTestProject>true</IsTestProject>`n"
    }
    if ([string]::IsNullOrWhiteSpace($extraProps)) {
        $extraProps = "    <!-- shared compilation settings inherited from Directory.Build.props -->`n"
    }

    $template = @'
<Project Sdk="__SDK__">

  <PropertyGroup>
__EXTRA_PROPS__  </PropertyGroup>

  <ItemGroup>
__REFS__
  </ItemGroup>

  <ItemGroup>
__PKGS__
  </ItemGroup>

</Project>
'@

    $template.Replace('__SDK__', $Def.Sdk).
        Replace('__EXTRA_PROPS__', $extraProps).
        Replace('__REFS__', ($refLines -join "`n")).
        Replace('__PKGS__', ($pkgLines -join "`n"))
}

function Write-MarkerFile {
    param([Parameter(Mandatory)]$Def)
    $ns = $Def.Name
    $content = @"
namespace $ns;

/// <summary>
/// Marker type used to identify this assembly for architecture testing and reflection-based discovery.
/// Intentionally empty: no domain behavior is introduced during solution scaffolding
/// (docs/architecture/06-solution-structure.md §47-48).
/// </summary>
public sealed class AssemblyMarker
{
}
"@
    Write-TextFile -Path (Join-Path $root "$($Def.Dir)/AssemblyMarker.cs") -Content $content
}

function Write-ApplicationDi {
    param([Parameter(Mandatory)][string]$Module)
    $name = "Yunu.Commerce.$Module.Application"
    $content = @"
using Microsoft.Extensions.DependencyInjection;

namespace $name;

/// <summary>
/// Composition entry point for the $Module Application layer (docs §49).
/// Hosts call this extension to register use case handlers and application services.
/// No use case implementation is registered yet during the architecture skeleton phase.
/// </summary>
public static class ${Module}ApplicationServiceCollectionExtensions
{
    public static IServiceCollection Add${Module}Application(this IServiceCollection services)
    {
        return services;
    }
}
"@
    Write-TextFile -Path (Join-Path $root "src/Modules/$Module/$name/${Module}ApplicationServiceCollectionExtensions.cs") -Content $content
}

function Write-InfrastructureDi {
    param([Parameter(Mandatory)][string]$Module)
    $name = "Yunu.Commerce.$Module.Infrastructure"
    $content = @"
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace $name;

/// <summary>
/// Composition entry point for the $Module Infrastructure layer (docs §49).
/// Hosts call this extension to register adapters implementing the module's ports.
/// No persistence, messaging or external provider adapter is wired yet during the
/// architecture skeleton phase (docs/architecture/06-solution-structure.md §55-56).
/// </summary>
public static class ${Module}InfrastructureServiceCollectionExtensions
{
    public static IServiceCollection Add${Module}Infrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        return services;
    }
}
"@
    Write-TextFile -Path (Join-Path $root "src/Modules/$Module/$name/${Module}InfrastructureServiceCollectionExtensions.cs") -Content $content
}

function Write-PlaceholderTest {
    param([Parameter(Mandatory)][string]$Namespace, [Parameter(Mandatory)][string]$Path)
    $content = @'
using Xunit;

namespace __NAMESPACE__;

public class PlaceholderTests
{
    [Fact]
    public void Placeholder_Should_Pass()
    {
        Assert.True(true);
    }
}
'@
    $content = $content.Replace('__NAMESPACE__', $Namespace)
    Write-TextFile -Path $Path -Content $content
}

# ---------------------------------------------------------------------------
# 1. Root configuration files
# ---------------------------------------------------------------------------

Write-Host "== Writing root configuration files ==" -ForegroundColor Yellow

Write-TextFile -Path "$root/global.json" -Content @'
{
  "sdk": {
    "version": "9.0.100",
    "rollForward": "latestFeature"
  }
}
'@

Write-TextFile -Path "$root/Directory.Build.props" -Content @'
<Project>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

</Project>
'@

Write-TextFile -Path "$root/Directory.Packages.props" -Content @'
<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="9.0.0" />
    <PackageVersion Include="OpenTelemetry" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.9.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.Console" Version="1.9.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="xunit" Version="2.9.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageVersion Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>

</Project>
'@

# ---------------------------------------------------------------------------
# 2. BuildingBlocks source content
# ---------------------------------------------------------------------------

Write-Host "== Writing BuildingBlocks source ==" -ForegroundColor Yellow

Write-TextFile -Path "$root/src/BuildingBlocks/Yunu.Commerce.SharedKernel/IDomainEvent.cs" -Content @'
namespace Yunu.Commerce.SharedKernel;

/// <summary>
/// Minimal, technology-agnostic marker for a domain event.
/// Intentionally free of any Bounded Context business concept
/// (docs/architecture/06-solution-structure.md §10).
/// </summary>
public interface IDomainEvent
{
    Guid EventId { get; }

    DateTimeOffset OccurredAtUtc { get; }
}
'@

Write-TextFile -Path "$root/src/BuildingBlocks/Yunu.Commerce.Contracts/IntegrationEventEnvelope.cs" -Content @'
namespace Yunu.Commerce.Contracts;

/// <summary>
/// Platform-level technical envelope for integration events exchanged between Bounded Contexts
/// (docs/architecture/06-solution-structure.md §11, .github/copilot-instructions.md §14).
/// Business-specific event payloads are owned by their respective module Contracts project.
/// </summary>
public sealed class IntegrationEventEnvelope
{
    public required Guid EventId { get; init; }

    public required string EventType { get; init; }

    public required string AggregateId { get; init; }

    public required string AggregateType { get; init; }

    public required string CorrelationId { get; init; }

    public string? CausationId { get; init; }

    public required DateTimeOffset OccurredAtUtc { get; init; }

    public required int SchemaVersion { get; init; }

    public required string Source { get; init; }

    public required object Data { get; init; }
}
'@

Write-TextFile -Path "$root/src/BuildingBlocks/Yunu.Commerce.EventBus/IIntegrationEventPublisher.cs" -Content @'
using Yunu.Commerce.Contracts;

namespace Yunu.Commerce.EventBus;

/// <summary>
/// Messaging abstraction for publishing integration events (docs §12).
/// Broker-specific implementations (e.g. Kafka) must live in module Infrastructure
/// projects only, never in Domain or Application.
/// </summary>
public interface IIntegrationEventPublisher
{
    Task PublishAsync(IntegrationEventEnvelope envelope, CancellationToken cancellationToken);
}
'@

Write-TextFile -Path "$root/src/BuildingBlocks/Yunu.Commerce.Security/ICurrentUserContext.cs" -Content @'
namespace Yunu.Commerce.Security;

/// <summary>
/// Technical abstraction for the current authenticated principal (docs §14).
/// Identity provider-specific implementation (e.g. Microsoft Entra ID) is an
/// outer infrastructure concern and must not leak here.
/// </summary>
public interface ICurrentUserContext
{
    string? UserId { get; }

    bool IsAuthenticated { get; }
}
'@

Write-TextFile -Path "$root/src/BuildingBlocks/Yunu.Commerce.Observability/ObservabilityServiceCollectionExtensions.cs" -Content @'
using Microsoft.Extensions.DependencyInjection;
using OpenTelemetry.Metrics;
using OpenTelemetry.Resources;
using OpenTelemetry.Trace;

namespace Yunu.Commerce.Observability;

/// <summary>
/// Reusable OpenTelemetry bootstrap shared across Hosts (docs §13).
/// Exporters are minimal (console) until a collector endpoint is defined by
/// deployment configuration; this must not contain business-specific telemetry logic.
/// </summary>
public static class ObservabilityServiceCollectionExtensions
{
    public static IServiceCollection AddYunuObservability(this IServiceCollection services, string serviceName)
    {
        services.AddOpenTelemetry()
            .WithTracing(tracing => tracing
                .AddSource(serviceName)
                .ConfigureResource(resource => resource.AddService(serviceName))
                .AddConsoleExporter())
            .WithMetrics(metrics => metrics
                .ConfigureResource(resource => resource.AddService(serviceName))
                .AddConsoleExporter());

        return services;
    }
}
'@

# ---------------------------------------------------------------------------
# 3. Module source content (DI extensions + assembly markers)
# ---------------------------------------------------------------------------

Write-Host "== Writing module DI extension points ==" -ForegroundColor Yellow

foreach ($m in $businessModules) {
    Write-MarkerFile -Def $projects["Yunu.Commerce.$m.Domain"]
    Write-MarkerFile -Def $projects["Yunu.Commerce.$m.Contracts"]
    Write-ApplicationDi -Module $m
    Write-InfrastructureDi -Module $m
}

foreach ($m in $supportModules) {
    Write-MarkerFile -Def $projects["Yunu.Commerce.$m.Contracts"]
    Write-ApplicationDi -Module $m
    Write-InfrastructureDi -Module $m
}

# ---------------------------------------------------------------------------
# 4. Hosts
# ---------------------------------------------------------------------------

Write-Host "== Writing Hosts ==" -ForegroundColor Yellow

$usingsBlock = ($allModules | ForEach-Object {
    "using Yunu.Commerce.$_.Application;`nusing Yunu.Commerce.$_.Infrastructure;"
}) -join "`n"

$appChainBlock = ($allModules | ForEach-Object { "    .Add${_}Application()" }) -join "`n"
$infraChainBlock = ($allModules | ForEach-Object { "    .Add${_}Infrastructure(builder.Configuration)" }) -join "`n"

$apiProgram = @'
using Yunu.Commerce.Observability;
__USINGS__

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddYunuObservability("Yunu.Commerce.Api");

builder.Services
__APP_CHAIN__;

builder.Services
__INFRA_CHAIN__;

builder.Services.AddHealthChecks();

var app = builder.Build();

app.MapHealthChecks("/health/live");
app.MapHealthChecks("/health/ready");

app.MapGet("/", () => Results.Ok(new { service = "Yunu.Commerce.Api", status = "running" }));

app.Run();
'@
$apiProgram = $apiProgram.Replace('__USINGS__', $usingsBlock).
    Replace('__APP_CHAIN__', $appChainBlock).
    Replace('__INFRA_CHAIN__', $infraChainBlock)

Write-TextFile -Path "$root/src/Hosts/Yunu.Commerce.Api/Program.cs" -Content $apiProgram

$workerProgram = @'
using Yunu.Commerce.Observability;
using Yunu.Commerce.Worker;
__USINGS__

var builder = Host.CreateApplicationBuilder(args);

builder.Services.AddYunuObservability("Yunu.Commerce.Worker");

builder.Services
__APP_CHAIN__;

builder.Services
__INFRA_CHAIN__;

builder.Services.AddHealthChecks();

builder.Services.AddHostedService<Worker>();

var host = builder.Build();

host.Run();
'@
$workerProgram = $workerProgram.Replace('__USINGS__', $usingsBlock).
    Replace('__APP_CHAIN__', $appChainBlock).
    Replace('__INFRA_CHAIN__', $infraChainBlock)

Write-TextFile -Path "$root/src/Hosts/Yunu.Commerce.Worker/Program.cs" -Content $workerProgram

Write-TextFile -Path "$root/src/Hosts/Yunu.Commerce.Worker/Worker.cs" -Content @'
namespace Yunu.Commerce.Worker;

/// <summary>
/// Placeholder background service. Concrete Kafka consumers, Outbox and Inbox
/// processors will be added incrementally once module Infrastructure adapters
/// are implemented (docs/architecture/06-solution-structure.md §8).
/// </summary>
public sealed class Worker : BackgroundService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            _logger.LogInformation("Yunu.Commerce.Worker heartbeat at {TimestampUtc}", DateTimeOffset.UtcNow);
            await Task.Delay(TimeSpan.FromMinutes(5), stoppingToken);
        }
    }
}
'@

# ---------------------------------------------------------------------------
# 5. Tests
# ---------------------------------------------------------------------------

Write-Host "== Writing Tests ==" -ForegroundColor Yellow

Write-TextFile -Path "$root/tests/Architecture/Yunu.Commerce.ArchitectureTests/DependencyRuleTests.cs" -Content @'
using System.Linq;
using System.Reflection;
using NetArchTest.Rules;
using Xunit;

namespace Yunu.Commerce.ArchitectureTests;

/// <summary>
/// Enforces the Clean Architecture / Hexagonal dependency rules defined in
/// docs/architecture/06-solution-structure.md §27-34 and .github/copilot-instructions.md §4/§37.
/// </summary>
public class DependencyRuleTests
{
    private static readonly string[] BusinessModules =
    {
        "Catalog", "Sellers", "Offers", "Pricing", "Availability", "Fulfillment", "Freight"
    };

    private static readonly string[] SupportModules =
    {
        "Search", "AI", "Integrations"
    };

    private static readonly string[] ForbiddenVendorNamespaces =
    {
        "Microsoft.AspNetCore",
        "MongoDB.Driver",
        "Confluent.Kafka",
        "StackExchange.Redis",
        "Elasticsearch",
        "Nest",
        "Azure.AI",
        "Microsoft.Azure",
        "Google.Cloud",
        "Google.Apis"
    };

    private static Assembly LoadAssembly(string name) => Assembly.Load(name);

    public static IEnumerable<object[]> BusinessModuleNames()
        => BusinessModules.Select(m => new object[] { m });

    public static IEnumerable<object[]> AllModuleNames()
        => BusinessModules.Concat(SupportModules).Select(m => new object[] { m });

    [Theory]
    [MemberData(nameof(BusinessModuleNames))]
    public void Domain_Should_Not_Depend_On_Application(string module)
    {
        var domain = LoadAssembly($"Yunu.Commerce.{module}.Domain");

        var result = Types.InAssembly(domain)
            .ShouldNot()
            .HaveDependencyOn($"Yunu.Commerce.{module}.Application")
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Theory]
    [MemberData(nameof(BusinessModuleNames))]
    public void Domain_Should_Not_Depend_On_Infrastructure(string module)
    {
        var domain = LoadAssembly($"Yunu.Commerce.{module}.Domain");

        var result = Types.InAssembly(domain)
            .ShouldNot()
            .HaveDependencyOn($"Yunu.Commerce.{module}.Infrastructure")
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Theory]
    [MemberData(nameof(BusinessModuleNames))]
    public void Domain_Should_Not_Depend_On_Vendor_Infrastructure(string module)
    {
        var domain = LoadAssembly($"Yunu.Commerce.{module}.Domain");

        var result = Types.InAssembly(domain)
            .ShouldNot()
            .HaveDependencyOnAny(ForbiddenVendorNamespaces)
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Theory]
    [MemberData(nameof(AllModuleNames))]
    public void Application_Should_Not_Depend_On_Infrastructure(string module)
    {
        var application = LoadAssembly($"Yunu.Commerce.{module}.Application");

        var result = Types.InAssembly(application)
            .ShouldNot()
            .HaveDependencyOn($"Yunu.Commerce.{module}.Infrastructure")
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Theory]
    [MemberData(nameof(AllModuleNames))]
    public void Application_Should_Not_Depend_On_Vendor_Infrastructure(string module)
    {
        var application = LoadAssembly($"Yunu.Commerce.{module}.Application");

        var result = Types.InAssembly(application)
            .ShouldNot()
            .HaveDependencyOnAny(ForbiddenVendorNamespaces)
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Fact]
    public void No_BoundedContext_Domain_Should_Depend_On_Another_BoundedContext_Domain()
    {
        foreach (var module in BusinessModules)
        {
            var domain = LoadAssembly($"Yunu.Commerce.{module}.Domain");

            foreach (var otherModule in BusinessModules.Where(m => m != module))
            {
                var result = Types.InAssembly(domain)
                    .ShouldNot()
                    .HaveDependencyOn($"Yunu.Commerce.{otherModule}")
                    .GetResult();

                Assert.True(result.IsSuccessful, Describe(result));
            }
        }
    }

    [Fact]
    public void Search_Application_Should_Not_Depend_On_Elasticsearch()
    {
        var application = LoadAssembly("Yunu.Commerce.Search.Application");

        var result = Types.InAssembly(application)
            .ShouldNot()
            .HaveDependencyOnAny("Elasticsearch", "Nest")
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    [Fact]
    public void AI_Application_Should_Not_Depend_On_Cloud_AI_Providers()
    {
        var application = LoadAssembly("Yunu.Commerce.AI.Application");

        var result = Types.InAssembly(application)
            .ShouldNot()
            .HaveDependencyOnAny("Azure.AI", "Microsoft.Azure", "Google.Cloud", "Google.Apis")
            .GetResult();

        Assert.True(result.IsSuccessful, Describe(result));
    }

    private static string Describe(TestResult result)
        => result.FailingTypes is null
            ? "Architecture rule violated."
            : "Architecture rule violated by: " + string.Join(", ", result.FailingTypes.Select(t => t.FullName));
}
'@

foreach ($m in $businessModules) {
    Write-PlaceholderTest -Namespace "Yunu.Commerce.$m.Domain.Tests" `
        -Path "$root/tests/Unit/Yunu.Commerce.$m.Domain.Tests/PlaceholderTests.cs"
}

Write-PlaceholderTest -Namespace 'Yunu.Commerce.Catalog.Application.Tests' `
    -Path "$root/tests/Unit/Yunu.Commerce.Catalog.Application.Tests/PlaceholderTests.cs"

Write-PlaceholderTest -Namespace 'Yunu.Commerce.IntegrationTests' `
    -Path "$root/tests/Integration/Yunu.Commerce.IntegrationTests/PlaceholderTests.cs"

# ---------------------------------------------------------------------------
# 6. csproj files (written last so the registry above is complete)
# ---------------------------------------------------------------------------

Write-Host "== Writing .csproj files ==" -ForegroundColor Yellow

foreach ($key in $projects.Keys) {
    $def = $projects[$key]
    $csprojPath = Join-Path $root "$($def.Dir)/$($def.Name).csproj"
    Write-TextFile -Path $csprojPath -Content (New-CsprojContent -Def $def)
}

# ---------------------------------------------------------------------------
# 7. .editorconfig
# ---------------------------------------------------------------------------

Write-TextFile -Path "$root/.editorconfig" -Content @'
root = true

[*]
indent_style = space
indent_size = 4
charset = utf-8-bom
trim_trailing_whitespace = true
insert_final_newline = true

[*.{csproj,props,targets}]
indent_size = 2

[*.json]
indent_size = 2

[*.md]
trim_trailing_whitespace = false

[*.cs]
csharp_new_line_before_open_brace = all
csharp_prefer_braces = true:suggestion
csharp_style_var_for_built_in_types = true:suggestion
csharp_style_var_when_type_is_apparent = true:suggestion
csharp_style_namespace_declarations = file_scoped:suggestion
dotnet_sort_system_directives_first = true
dotnet_style_qualification_for_field = false:suggestion
dotnet_style_qualification_for_property = false:suggestion
dotnet_style_qualification_for_method = false:suggestion
dotnet_style_require_accessibility_modifiers = for_non_interface_members:suggestion
dotnet_style_predefined_type_for_locals_parameters_members = true:suggestion

# Interfaces start with I
dotnet_naming_rule.interfaces_start_with_i.severity = warning
dotnet_naming_rule.interfaces_start_with_i.symbols = interface_symbol
dotnet_naming_rule.interfaces_start_with_i.style = interface_style
dotnet_naming_symbols.interface_symbol.applicable_kinds = interface
dotnet_naming_style.interface_style.required_prefix = I
dotnet_naming_style.interface_style.capitalization = pascal_case

# Async methods end with Async
dotnet_naming_rule.async_methods_end_in_async.severity = suggestion
dotnet_naming_rule.async_methods_end_in_async.symbols = async_method_symbol
dotnet_naming_rule.async_methods_end_in_async.style = async_method_style
dotnet_naming_symbols.async_method_symbol.applicable_kinds = method
dotnet_naming_symbols.async_method_symbol.required_modifiers = async
dotnet_naming_style.async_method_style.required_suffix = Async
dotnet_naming_style.async_method_style.capitalization = pascal_case
'@

# ---------------------------------------------------------------------------
# 8. Solution file + Solution Folders + project registration
# ---------------------------------------------------------------------------

Write-Host "== Creating solution and registering projects ==" -ForegroundColor Yellow

if (-not (Test-Path "$root/Yunu.Commerce.sln")) {
    Invoke-Checked -Exe 'dotnet' -Arguments @('new', 'sln', '--name', 'Yunu.Commerce')
}

foreach ($key in $projects.Keys) {
    $def = $projects[$key]
    $csprojPath = "$($def.Dir)/$($def.Name).csproj"
    Invoke-Checked -Exe 'dotnet' -Arguments @(
        'sln', 'Yunu.Commerce.sln', 'add', $csprojPath,
        '--solution-folder', $def.SolutionFolder
    )
}

# ---------------------------------------------------------------------------
# 9. Restore / Build / Test
# ---------------------------------------------------------------------------

try {
    Invoke-Checked -Exe 'dotnet' -Arguments @('restore', 'Yunu.Commerce.sln')

    if (-not $SkipBuild) {
        Invoke-Checked -Exe 'dotnet' -Arguments @('build', 'Yunu.Commerce.sln', '--no-restore', '-c', 'Debug')
    }

    if (-not $SkipTest -and -not $SkipBuild) {
        Invoke-Checked -Exe 'dotnet' -Arguments @('test', 'Yunu.Commerce.sln', '--no-build', '-c', 'Debug')
    }

    Write-Host ""
    Write-Host "Yunu.Commerce solution skeleton created and verified successfully." -ForegroundColor Green
}
catch {
    Write-Host ""
    Write-Host "Bootstrap failed: $($_.Exception.Message)" -ForegroundColor Red
    exit 1
}